INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (61,'Santana Feat. Everlast')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (265,'Julian Bream')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (183,'Gustavo & Andres Veiga & Salazar')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (122,'R.E.M. Feat. Kate Pearson')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (40,'Os Cariocas')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (244,'Choir Of Westminster Abbey & Simon Preston')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (162,'Los Lonely Boys')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (101,'Lulu Santos')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (223,'London Symphony Orchestra & Sir Charles Mackerras')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (141,'The Police')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (19,'Cidade Negra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (263,'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (80,'Djavan')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (120,'Pink Floyd')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (202,'Aaron Goldberg')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (99,'Legião Urbana')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (59,'Santana')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (160,'Christina Aguilera featuring BigElf')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (181,'Xis')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (17,'Chico Buarque')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (242,'Edo de Waart & San Francisco Symphony')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (139,'The Cult')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (38,'Banda Black Rio')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (261,'Roger Norrington, London Classical Players')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (221,'Sir Georg Solti & Wiener Philharmoniker')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (118,'Pearl Jam')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (78,'Def Leppard')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (179,'Scorpions')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (200,'The Posies')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (158,'Battlestar Galactica (Classic)')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (57,'Os Mutantes')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (15,'Buddy Guy')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (240,'Gustav Mahler')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (137,'The Black Crowes')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (36,'O Rappa')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (177,'Jack''s Mannequin & Mick Fleetwood')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (97,'João Suplicy')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (34,'Nando Reis')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (219,'Britten Sinfonia, Ivor Bolton & Lesley Garrett')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (156,'The Office')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (76,'Creedence Clearwater Revival')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (13,'Body Count')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (198,'Habib Koité and Bamada')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (135,'System Of A Down')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (259,'The 12 Cellists of The Berlin Philharmonic')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (196,'Cake')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (55,'David Coverdale')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (53,'Spyro Gyra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (116,'Passengers')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (175,'Jaguares')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (238,'Maurizio Pollini')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (32,'Ney Matogrosso')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (95,'Joe Satriani')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (154,'Whitesnake')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (217,'Royal Philharmonic Orchestra & Sir Thomas Beecham')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (215,'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (74,'Vinícius E Odette Lara')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (11,'Black Label Society')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (257,'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (194,'Sabotage E Instituto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (114,'Ozzy Osbourne')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (51,'Queen')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (236,'James Levine')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (173,'Matisyahu')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (93,'JET')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (30,'Jorge Vercilo')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (72,'Vinícius De Moraes')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (213,'Scholars Baroque Ensemble')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (133,'Stevie Ray Vaughan & Double Trouble')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (9,'BackBeat')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (255,'Yehudi Menuhin')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (70,'Toquinho & Vinícius')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (112,'Olodum')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (192,'DJ Dolores & Orchestra Santa Massa')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (234,'Orchestra of The Age of Enlightenment')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (49,'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (91,'James Brown')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (171,'Ben Harper')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (152,'Van Halen')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (232,'Sergei Prokofiev & Yuri Temirkanov')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (274,'Nash Ensemble')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (28,'João Gilberto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (131,'Smashing Pumpkins')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (89,'Incognito')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (253,'Calexico')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (211,'Wilhelm Kempff')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (110,'Nirvana')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (68,'Miles Davis')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (150,'U2')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (190,'Instituto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (7,'Apocalyptica')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (251,'Fretwork')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (272,'Emerson String Quartet')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (47,'Hermeto Pascoal')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (129,'Simply Red')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (230,'Aaron Copland & London Symphony Orchestra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (108,'Mônica Marianno')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (87,'Godsmack')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (169,'Black Eyed Peas')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (209,'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (26,'Azymuth')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (66,'Santana Feat. Eagle-Eye Cherry')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (148,'Heroes')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (249,'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (5,'Alice In Chains')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (45,'Sandra De Sá')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (270,'Gerald Moore')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (106,'Motörhead')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (127,'Red Hot Chili Peppers')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (228,'Leonard Bernstein & New York Philharmonic')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (188,'Mundo Livre S/A')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (85,'Frank Sinatra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (167,'Big & Rich')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (207,'Richard Marlow & The Choir of Trinity College, Cambridge')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (24,'Marcos Valle')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (268,'Itzhak Perlman')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (146,'Titãs')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (64,'Santana Feat. The Project G&B')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (3,'Aerosmith')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (125,'Raimundos')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (186,'Pedro Luís E A Parede')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (247,'The King''s Singers')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (43,'A Cor Do Som')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (104,'Marvin Gaye')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (165,'Jackson Browne')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (226,'Eugene Ormandy')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (22,'Led Zeppelin')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (83,'Falamansa')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (144,'The Who')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (266,'Martin Roscoe')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (205,'Chris Cornell')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (123,'R.E.M. Feat. KRS-One')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (1,'AC/DC')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (245,'Michael Tilson Thomas & San Francisco Symphony')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (62,'Santana Feat. Rob Thomas')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (102,'Marillion')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (184,'Rodox')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (81,'Eric Clapton')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (41,'Elis Regina')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (142,'The Rolling Stones')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (163,'Corinne Bailey Rae')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (264,'Kent Nagano and Orchestre de l''Opéra de Lyon')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (224,'Barry Wordsworth & BBC Concert Orchestra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (121,'Planet Hemp')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (20,'Cláudio Zoli')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (243,'Antal Doráti & London Symphony Orchestra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (203,'Nicolaus Esterhazy Sinfonia')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (100,'Lenny Kravitz')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (60,'Santana Feat. Dave Matthews')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (161,'Aerosmith & Sierra Leone''s Refugee Allstars')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (182,'Nega Gizza')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (140,'The Doors')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (39,'Fernanda Porto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (262,'Charles Dutoit & L''Orchestre Symphonique de Montréal')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (222,'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (119,'Peter Tosh')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (18,'Chico Science & Nação Zumbi')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (159,'Aquaman')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (79,'Dennis Chambers')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (16,'Caetano Veloso')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (201,'Luciana Souza/Romero Lubambo')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (138,'The Clash')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (58,'Deep Purple')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (117,'Paul D''Ianno')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (180,'House Of Pain')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (178,'Regina Spektor')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (241,'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (35,'Pedro Luís & A Parede')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (37,'Ed Motta')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (157,'Dread Zeppelin')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (98,'Judas Priest')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (14,'Bruce Dickinson')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (220,'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (136,'Terry Bozzio, Tony Levin & Steve Stevens')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (77,'Cássia Eller')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (197,'Aisha Duo')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (199,'Karsh Kale')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (176,'The Flaming Lips')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (260,'Adrian Leaper & Doreen de Feis')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (33,'Luiz Melodia')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (56,'Gonzaguinha')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (155,'Zeca Pagodinho')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (239,'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (12,'Black Sabbath')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (96,'Jota Quest')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (195,'Stereo Maracana')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (218,'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (52,'Kiss')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (75,'Vinicius, Toquinho & Quarteto Em Cy')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (174,'The Postal Service')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (258,'Les Arts Florissants & William Christie')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (31,'Baby Consuelo')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (54,'Green Day')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (153,'Velvet Revolver')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (115,'Page & Plant')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (214,'Academy of St. Martin in the Fields & Sir Neville Marriner')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (237,'Berliner Philharmoniker & Hans Rosbaud')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (10,'Billy Cobham')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (94,'Jimi Hendrix')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (71,'Vinícius De Moraes & Baden Powell')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (216,'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (193,'Seu Jorge')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (73,'Vinícius E Qurteto Em Cy')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (50,'Metallica')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (134,'Stone Temple Pilots')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (172,'Snow Patrol')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (256,'Philharmonia Orchestra & Sir Neville Marriner')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (233,'Chicago Symphony Orchestra & Fritz Reiner')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (113,'Os Paralamas Do Sucesso')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (29,'Bebel Gilberto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (235,'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (212,'Yo-Yo Ma')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (92,'Jamiroquai')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (69,'Gene Krupa')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (275,'Philip Glass Ensemble')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (191,'Nação Zumbi')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (132,'Soundgarden')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (48,'Barão Vermelho')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (254,'Otto Klemperer & Philharmonia Orchestra')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (231,'Ton Koopman')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (111,'O Terço')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (27,'Gilberto Gil')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (90,'Iron Maiden')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (88,'Guns N'' Roses')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (151,'UB40')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (210,'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (8,'Audioslave')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (67,'Santana Feat. Eric Clapton')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (273,'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (189,'Otto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (130,'Skank')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (250,'Christopher O''Riley')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (252,'Amy Winehouse')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (46,'Jorge Ben')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (109,'Mötley Crüe')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (107,'Motörhead & Girlschool')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (170,'Jack Johnson')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (229,'Boston Symphony Orchestra & Seiji Ozawa')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (149,'Lost')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (86,'Funk Como Le Gusta')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (6,'Antônio Carlos Jobim')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (208,'English Concert & Trevor Pinnock')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (271,'Mela Tenenbaum, Pro Musica Prague & Richard Kapp')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (269,'Michele Campanella')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (128,'Rush')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (65,'Santana Feat. Maná')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (168,'Youssou N''Dour')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (248,'Berliner Philharmoniker & Herbert Von Karajan')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (25,'Milton Nascimento & Bebeto')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (105,'Men At Work')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (147,'Battlestar Galactica')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (227,'Luciano Pavarotti')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (4,'Alanis Morissette')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (84,'Foo Fighters')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (126,'Raul Seixas')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (267,'Göteborgs Symfoniker & Neeme Järvi')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (187,'Los Hermanos')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (63,'Santana Feat. Lauryn Hill & Cee-Lo')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (44,'Kid Abelha')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (124,'R.E.M.')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (166,'Avril Lavigne')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (246,'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (23,'Frank Zappa & Captain Beefheart')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (103,'Marisa Monte')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (145,'Tim Maia')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (225,'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (206,'Alberto Turco & Nova Schola Gregoriana')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (82,'Faith No More')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (2,'Accept')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (143,'The Tea Party')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (185,'Charlie Brown Jr.')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (42,'Milton Nascimento')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (164,'Dhani Harrison & Jakob Dylan')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (21,'Various Artists')
;INSERT INTO "Chinook"."Artist" ("ArtistId","Name") VALUES (204,'Temple of the Dog');
