INSERT INTO "Artist" ("Name") VALUES ('Philip Glass Ensemble');
INSERT INTO "Artist" ("Name") VALUES ('Nash Ensemble');
INSERT INTO "Artist" ("Name") VALUES ('C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO "Artist" ("Name") VALUES ('Emerson String Quartet');
INSERT INTO "Artist" ("Name") VALUES ('Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO "Artist" ("Name") VALUES ('Gerald Moore');
INSERT INTO "Artist" ("Name") VALUES ('Michele Campanella');
INSERT INTO "Artist" ("Name") VALUES ('Itzhak Perlman');
INSERT INTO "Artist" ("Name") VALUES ('Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO "Artist" ("Name") VALUES ('Martin Roscoe');
INSERT INTO "Artist" ("Name") VALUES ('Julian Bream');
INSERT INTO "Artist" ("Name") VALUES ('Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO "Artist" ("Name") VALUES ('Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO "Artist" ("Name") VALUES ('Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO "Artist" ("Name") VALUES ('Roger Norrington, London Classical Players');
INSERT INTO "Artist" ("Name") VALUES ('Adrian Leaper & Doreen de Feis');
INSERT INTO "Artist" ("Name") VALUES ('The 12 Cellists of The Berlin Philharmonic');
INSERT INTO "Artist" ("Name") VALUES ('Les Arts Florissants & William Christie');
INSERT INTO "Artist" ("Name") VALUES ('Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO "Artist" ("Name") VALUES ('Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO "Artist" ("Name") VALUES ('Yehudi Menuhin');
INSERT INTO "Artist" ("Name") VALUES ('Otto Klemperer & Philharmonia Orchestra');
INSERT INTO "Artist" ("Name") VALUES ('Calexico');
INSERT INTO "Artist" ("Name") VALUES ('Amy Winehouse');
INSERT INTO "Artist" ("Name") VALUES ('Fretwork');
INSERT INTO "Artist" ("Name") VALUES ('Christopher O''Riley');
INSERT INTO "Artist" ("Name") VALUES ('Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO "Artist" ("Name") VALUES ('Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO "Artist" ("Name") VALUES ('The King''s Singers');
INSERT INTO "Artist" ("Name") VALUES ('Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "Artist" ("Name") VALUES ('Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO "Artist" ("Name") VALUES ('Choir Of Westminster Abbey & Simon Preston');
INSERT INTO "Artist" ("Name") VALUES ('Antal Doráti & London Symphony Orchestra');
INSERT INTO "Artist" ("Name") VALUES ('Edo de Waart & San Francisco Symphony');
INSERT INTO "Artist" ("Name") VALUES ('Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO "Artist" ("Name") VALUES ('Gustav Mahler');
INSERT INTO "Artist" ("Name") VALUES ('Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO "Artist" ("Name") VALUES ('Maurizio Pollini');
INSERT INTO "Artist" ("Name") VALUES ('Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO "Artist" ("Name") VALUES ('James Levine');
INSERT INTO "Artist" ("Name") VALUES ('Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO "Artist" ("Name") VALUES ('Orchestra of The Age of Enlightenment');
INSERT INTO "Artist" ("Name") VALUES ('Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO "Artist" ("Name") VALUES ('Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO "Artist" ("Name") VALUES ('Ton Koopman');
INSERT INTO "Artist" ("Name") VALUES ('Aaron Copland & London Symphony Orchestra');
INSERT INTO "Artist" ("Name") VALUES ('Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO "Artist" ("Name") VALUES ('Leonard Bernstein & New York Philharmonic');
INSERT INTO "Artist" ("Name") VALUES ('Luciano Pavarotti');
INSERT INTO "Artist" ("Name") VALUES ('Eugene Ormandy');
INSERT INTO "Artist" ("Name") VALUES ('Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO "Artist" ("Name") VALUES ('Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO "Artist" ("Name") VALUES ('London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO "Artist" ("Name") VALUES ('Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO "Artist" ("Name") VALUES ('Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO "Artist" ("Name") VALUES ('Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO "Artist" ("Name") VALUES ('Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO "Artist" ("Name") VALUES ('Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO "Artist" ("Name") VALUES ('Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO "Artist" ("Name") VALUES ('Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO "Artist" ("Name") VALUES ('Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO "Artist" ("Name") VALUES ('Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO "Artist" ("Name") VALUES ('Scholars Baroque Ensemble');
INSERT INTO "Artist" ("Name") VALUES ('Yo-Yo Ma');
INSERT INTO "Artist" ("Name") VALUES ('Wilhelm Kempff');
INSERT INTO "Artist" ("Name") VALUES ('Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO "Artist" ("Name") VALUES ('Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "Artist" ("Name") VALUES ('English Concert & Trevor Pinnock');
INSERT INTO "Artist" ("Name") VALUES ('Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO "Artist" ("Name") VALUES ('Alberto Turco & Nova Schola Gregoriana');
INSERT INTO "Artist" ("Name") VALUES ('Chris Cornell');
INSERT INTO "Artist" ("Name") VALUES ('Temple of the Dog');
INSERT INTO "Artist" ("Name") VALUES ('Nicolaus Esterhazy Sinfonia');
INSERT INTO "Artist" ("Name") VALUES ('Aaron Goldberg');
INSERT INTO "Artist" ("Name") VALUES ('Luciana Souza/Romero Lubambo');
INSERT INTO "Artist" ("Name") VALUES ('The Posies');
INSERT INTO "Artist" ("Name") VALUES ('Karsh Kale');
INSERT INTO "Artist" ("Name") VALUES ('Habib Koité and Bamada');
INSERT INTO "Artist" ("Name") VALUES ('Aisha Duo');
INSERT INTO "Artist" ("Name") VALUES ('Cake');
INSERT INTO "Artist" ("Name") VALUES ('Stereo Maracana');
INSERT INTO "Artist" ("Name") VALUES ('Sabotage E Instituto');
INSERT INTO "Artist" ("Name") VALUES ('Seu Jorge');
INSERT INTO "Artist" ("Name") VALUES ('DJ Dolores & Orchestra Santa Massa');
INSERT INTO "Artist" ("Name") VALUES ('Nação Zumbi');
INSERT INTO "Artist" ("Name") VALUES ('Instituto');
INSERT INTO "Artist" ("Name") VALUES ('Otto');
INSERT INTO "Artist" ("Name") VALUES ('Mundo Livre S/A');
INSERT INTO "Artist" ("Name") VALUES ('Los Hermanos');
INSERT INTO "Artist" ("Name") VALUES ('Pedro Luís E A Parede');
INSERT INTO "Artist" ("Name") VALUES ('Charlie Brown Jr.');
INSERT INTO "Artist" ("Name") VALUES ('Rodox');
INSERT INTO "Artist" ("Name") VALUES ('Gustavo & Andres Veiga & Salazar');
INSERT INTO "Artist" ("Name") VALUES ('Nega Gizza');
INSERT INTO "Artist" ("Name") VALUES ('Xis');
INSERT INTO "Artist" ("Name") VALUES ('House Of Pain');
INSERT INTO "Artist" ("Name") VALUES ('Scorpions');
INSERT INTO "Artist" ("Name") VALUES ('Regina Spektor');
INSERT INTO "Artist" ("Name") VALUES ('Jack''s Mannequin & Mick Fleetwood');
INSERT INTO "Artist" ("Name") VALUES ('The Flaming Lips');
INSERT INTO "Artist" ("Name") VALUES ('Jaguares');
INSERT INTO "Artist" ("Name") VALUES ('The Postal Service');
INSERT INTO "Artist" ("Name") VALUES ('Matisyahu');
INSERT INTO "Artist" ("Name") VALUES ('Snow Patrol');
INSERT INTO "Artist" ("Name") VALUES ('Ben Harper');
INSERT INTO "Artist" ("Name") VALUES ('Jack Johnson');
INSERT INTO "Artist" ("Name") VALUES ('Black Eyed Peas');
INSERT INTO "Artist" ("Name") VALUES ('Youssou N''Dour');
INSERT INTO "Artist" ("Name") VALUES ('Big & Rich');
INSERT INTO "Artist" ("Name") VALUES ('Avril Lavigne');
INSERT INTO "Artist" ("Name") VALUES ('Jackson Browne');
INSERT INTO "Artist" ("Name") VALUES ('Dhani Harrison & Jakob Dylan');
INSERT INTO "Artist" ("Name") VALUES ('Corinne Bailey Rae');
INSERT INTO "Artist" ("Name") VALUES ('Los Lonely Boys');
INSERT INTO "Artist" ("Name") VALUES ('Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO "Artist" ("Name") VALUES ('Christina Aguilera featuring BigElf');
INSERT INTO "Artist" ("Name") VALUES ('Aquaman');
INSERT INTO "Artist" ("Name") VALUES ('Battlestar Galactica (Classic)');
INSERT INTO "Artist" ("Name") VALUES ('Dread Zeppelin');
INSERT INTO "Artist" ("Name") VALUES ('The Office');
INSERT INTO "Artist" ("Name") VALUES ('Zeca Pagodinho');
INSERT INTO "Artist" ("Name") VALUES ('Whitesnake');
INSERT INTO "Artist" ("Name") VALUES ('Velvet Revolver');
INSERT INTO "Artist" ("Name") VALUES ('Van Halen');
INSERT INTO "Artist" ("Name") VALUES ('UB40');
INSERT INTO "Artist" ("Name") VALUES ('U2');
INSERT INTO "Artist" ("Name") VALUES ('Lost');
INSERT INTO "Artist" ("Name") VALUES ('Heroes');
INSERT INTO "Artist" ("Name") VALUES ('Battlestar Galactica');
INSERT INTO "Artist" ("Name") VALUES ('Titãs');
INSERT INTO "Artist" ("Name") VALUES ('Tim Maia');
INSERT INTO "Artist" ("Name") VALUES ('The Who');
INSERT INTO "Artist" ("Name") VALUES ('The Tea Party');
INSERT INTO "Artist" ("Name") VALUES ('The Rolling Stones');
INSERT INTO "Artist" ("Name") VALUES ('The Police');
INSERT INTO "Artist" ("Name") VALUES ('The Doors');
INSERT INTO "Artist" ("Name") VALUES ('The Cult');
INSERT INTO "Artist" ("Name") VALUES ('The Clash');
INSERT INTO "Artist" ("Name") VALUES ('The Black Crowes');
INSERT INTO "Artist" ("Name") VALUES ('Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO "Artist" ("Name") VALUES ('System Of A Down');
INSERT INTO "Artist" ("Name") VALUES ('Stone Temple Pilots');
INSERT INTO "Artist" ("Name") VALUES ('Stevie Ray Vaughan & Double Trouble');
INSERT INTO "Artist" ("Name") VALUES ('Soundgarden');
INSERT INTO "Artist" ("Name") VALUES ('Smashing Pumpkins');
INSERT INTO "Artist" ("Name") VALUES ('Skank');
INSERT INTO "Artist" ("Name") VALUES ('Simply Red');
INSERT INTO "Artist" ("Name") VALUES ('Rush');
INSERT INTO "Artist" ("Name") VALUES ('Red Hot Chili Peppers');
INSERT INTO "Artist" ("Name") VALUES ('Raul Seixas');
INSERT INTO "Artist" ("Name") VALUES ('Raimundos');
INSERT INTO "Artist" ("Name") VALUES ('R.E.M.');
INSERT INTO "Artist" ("Name") VALUES ('R.E.M. Feat. KRS-One');
INSERT INTO "Artist" ("Name") VALUES ('R.E.M. Feat. Kate Pearson');
INSERT INTO "Artist" ("Name") VALUES ('Planet Hemp');
INSERT INTO "Artist" ("Name") VALUES ('Pink Floyd');
INSERT INTO "Artist" ("Name") VALUES ('Peter Tosh');
INSERT INTO "Artist" ("Name") VALUES ('Pearl Jam');
INSERT INTO "Artist" ("Name") VALUES ('Paul D''Ianno');
INSERT INTO "Artist" ("Name") VALUES ('Passengers');
INSERT INTO "Artist" ("Name") VALUES ('Page & Plant');
INSERT INTO "Artist" ("Name") VALUES ('Ozzy Osbourne');
INSERT INTO "Artist" ("Name") VALUES ('Os Paralamas Do Sucesso');
INSERT INTO "Artist" ("Name") VALUES ('Olodum');
INSERT INTO "Artist" ("Name") VALUES ('O Terço');
INSERT INTO "Artist" ("Name") VALUES ('Nirvana');
INSERT INTO "Artist" ("Name") VALUES ('Mötley Crüe');
INSERT INTO "Artist" ("Name") VALUES ('Mônica Marianno');
INSERT INTO "Artist" ("Name") VALUES ('Motörhead & Girlschool');
INSERT INTO "Artist" ("Name") VALUES ('Motörhead');
INSERT INTO "Artist" ("Name") VALUES ('Men At Work');
INSERT INTO "Artist" ("Name") VALUES ('Marvin Gaye');
INSERT INTO "Artist" ("Name") VALUES ('Marisa Monte');
INSERT INTO "Artist" ("Name") VALUES ('Marillion');
INSERT INTO "Artist" ("Name") VALUES ('Lulu Santos');
INSERT INTO "Artist" ("Name") VALUES ('Lenny Kravitz');
INSERT INTO "Artist" ("Name") VALUES ('Legião Urbana');
INSERT INTO "Artist" ("Name") VALUES ('Judas Priest');
INSERT INTO "Artist" ("Name") VALUES ('João Suplicy');
INSERT INTO "Artist" ("Name") VALUES ('Jota Quest');
INSERT INTO "Artist" ("Name") VALUES ('Joe Satriani');
INSERT INTO "Artist" ("Name") VALUES ('Jimi Hendrix');
INSERT INTO "Artist" ("Name") VALUES ('JET');
INSERT INTO "Artist" ("Name") VALUES ('Jamiroquai');
INSERT INTO "Artist" ("Name") VALUES ('James Brown');
INSERT INTO "Artist" ("Name") VALUES ('Iron Maiden');
INSERT INTO "Artist" ("Name") VALUES ('Incognito');
INSERT INTO "Artist" ("Name") VALUES ('Guns N'' Roses');
INSERT INTO "Artist" ("Name") VALUES ('Godsmack');
INSERT INTO "Artist" ("Name") VALUES ('Funk Como Le Gusta');
INSERT INTO "Artist" ("Name") VALUES ('Frank Sinatra');
INSERT INTO "Artist" ("Name") VALUES ('Foo Fighters');
INSERT INTO "Artist" ("Name") VALUES ('Falamansa');
INSERT INTO "Artist" ("Name") VALUES ('Faith No More');
INSERT INTO "Artist" ("Name") VALUES ('Eric Clapton');
INSERT INTO "Artist" ("Name") VALUES ('Djavan');
INSERT INTO "Artist" ("Name") VALUES ('Dennis Chambers');
INSERT INTO "Artist" ("Name") VALUES ('Def Leppard');
INSERT INTO "Artist" ("Name") VALUES ('Cássia Eller');
INSERT INTO "Artist" ("Name") VALUES ('Creedence Clearwater Revival');
INSERT INTO "Artist" ("Name") VALUES ('Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO "Artist" ("Name") VALUES ('Vinícius E Odette Lara');
INSERT INTO "Artist" ("Name") VALUES ('Vinícius E Qurteto Em Cy');
INSERT INTO "Artist" ("Name") VALUES ('Vinícius De Moraes');
INSERT INTO "Artist" ("Name") VALUES ('Vinícius De Moraes & Baden Powell');
INSERT INTO "Artist" ("Name") VALUES ('Toquinho & Vinícius');
INSERT INTO "Artist" ("Name") VALUES ('Gene Krupa');
INSERT INTO "Artist" ("Name") VALUES ('Miles Davis');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Eric Clapton');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Eagle-Eye Cherry');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Maná');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. The Project G&B');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Rob Thomas');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Everlast');
INSERT INTO "Artist" ("Name") VALUES ('Santana Feat. Dave Matthews');
INSERT INTO "Artist" ("Name") VALUES ('Santana');
INSERT INTO "Artist" ("Name") VALUES ('Deep Purple');
INSERT INTO "Artist" ("Name") VALUES ('Os Mutantes');
INSERT INTO "Artist" ("Name") VALUES ('Gonzaguinha');
INSERT INTO "Artist" ("Name") VALUES ('David Coverdale');
INSERT INTO "Artist" ("Name") VALUES ('Green Day');
INSERT INTO "Artist" ("Name") VALUES ('Spyro Gyra');
INSERT INTO "Artist" ("Name") VALUES ('Kiss');
INSERT INTO "Artist" ("Name") VALUES ('Queen');
INSERT INTO "Artist" ("Name") VALUES ('Metallica');
INSERT INTO "Artist" ("Name") VALUES ('Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO "Artist" ("Name") VALUES ('Barão Vermelho');
INSERT INTO "Artist" ("Name") VALUES ('Hermeto Pascoal');
INSERT INTO "Artist" ("Name") VALUES ('Jorge Ben');
INSERT INTO "Artist" ("Name") VALUES ('Sandra De Sá');
INSERT INTO "Artist" ("Name") VALUES ('Kid Abelha');
INSERT INTO "Artist" ("Name") VALUES ('A Cor Do Som');
INSERT INTO "Artist" ("Name") VALUES ('Milton Nascimento');
INSERT INTO "Artist" ("Name") VALUES ('Elis Regina');
INSERT INTO "Artist" ("Name") VALUES ('Os Cariocas');
INSERT INTO "Artist" ("Name") VALUES ('Fernanda Porto');
INSERT INTO "Artist" ("Name") VALUES ('Banda Black Rio');
INSERT INTO "Artist" ("Name") VALUES ('Ed Motta');
INSERT INTO "Artist" ("Name") VALUES ('O Rappa');
INSERT INTO "Artist" ("Name") VALUES ('Pedro Luís & A Parede');
INSERT INTO "Artist" ("Name") VALUES ('Nando Reis');
INSERT INTO "Artist" ("Name") VALUES ('Luiz Melodia');
INSERT INTO "Artist" ("Name") VALUES ('Ney Matogrosso');
INSERT INTO "Artist" ("Name") VALUES ('Baby Consuelo');
INSERT INTO "Artist" ("Name") VALUES ('Jorge Vercilo');
INSERT INTO "Artist" ("Name") VALUES ('Bebel Gilberto');
INSERT INTO "Artist" ("Name") VALUES ('João Gilberto');
INSERT INTO "Artist" ("Name") VALUES ('Gilberto Gil');
INSERT INTO "Artist" ("Name") VALUES ('Azymuth');
INSERT INTO "Artist" ("Name") VALUES ('Milton Nascimento & Bebeto');
INSERT INTO "Artist" ("Name") VALUES ('Marcos Valle');
INSERT INTO "Artist" ("Name") VALUES ('Frank Zappa & Captain Beefheart');
INSERT INTO "Artist" ("Name") VALUES ('Led Zeppelin');
INSERT INTO "Artist" ("Name") VALUES ('Various Artists');
INSERT INTO "Artist" ("Name") VALUES ('Cláudio Zoli');
INSERT INTO "Artist" ("Name") VALUES ('Cidade Negra');
INSERT INTO "Artist" ("Name") VALUES ('Chico Science & Nação Zumbi');
INSERT INTO "Artist" ("Name") VALUES ('Chico Buarque');
INSERT INTO "Artist" ("Name") VALUES ('Caetano Veloso');
INSERT INTO "Artist" ("Name") VALUES ('Buddy Guy');
INSERT INTO "Artist" ("Name") VALUES ('Bruce Dickinson');
INSERT INTO "Artist" ("Name") VALUES ('Body Count');
INSERT INTO "Artist" ("Name") VALUES ('Black Sabbath');
INSERT INTO "Artist" ("Name") VALUES ('Black Label Society');
INSERT INTO "Artist" ("Name") VALUES ('Billy Cobham');
INSERT INTO "Artist" ("Name") VALUES ('BackBeat');
INSERT INTO "Artist" ("Name") VALUES ('Audioslave');
INSERT INTO "Artist" ("Name") VALUES ('Apocalyptica');
INSERT INTO "Artist" ("Name") VALUES ('Antônio Carlos Jobim');
INSERT INTO "Artist" ("Name") VALUES ('Alice In Chains');
INSERT INTO "Artist" ("Name") VALUES ('Alanis Morissette');
INSERT INTO "Artist" ("Name") VALUES ('Aerosmith');
INSERT INTO "Artist" ("Name") VALUES ('Accept');
INSERT INTO "Artist" ("Name") VALUES ('AC/DC');
