INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (7,'Movies');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (17,'Heavy Metal Classic');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (5,'90’s Music');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (15,'Classical 101 - The Basics');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (3,'TV Shows');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (13,'Classical 101 - Deep Cuts');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (1,'Music');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (11,'Brazilian Music');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (18,'On-The-Go 1');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (9,'Music Videos');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (8,'Music');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (16,'Grunge');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (6,'Audiobooks');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (14,'Classical 101 - Next Steps');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (4,'Audiobooks');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (12,'Classical');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (2,'Movies');
INSERT INTO "Chinook"."Playlist" ("PlaylistId","Name") VALUES (10,'TV Shows');
