INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (19,'TV Shows');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (17,'Hip Hop/Rap');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (7,'Latin');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (15,'Electronica/Dance');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (5,'Rock And Roll');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (13,'Heavy Metal');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (24,'Classical');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (11,'Bossa Nova');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (3,'Metal');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (9,'Pop');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (22,'Comedy');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (16,'World');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (1,'Rock');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (14,'R&B/Soul');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (20,'Sci Fi & Fantasy');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (12,'Easy Listening');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (18,'Science Fiction');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (10,'Soundtrack');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (8,'Reggae');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (6,'Blues');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (25,'Opera');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (4,'Alternative & Punk');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (23,'Alternative');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (2,'Jazz');
INSERT INTO "Chinook"."Genre" ("GenreId","Name") VALUES (21,'Drama');
